services:
  stableviton:
    build: .
    stdin_open: true # docker run -i
    tty: true # docker run -t
    develop:
      watch:
        - action: sync
          path: .
          target: /StableVITON/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
